#!/usr/bin/env bash

# This script is used by MakeNote function to convert *.md files
# inside the current directory into html notes linked as a wiki.
# As alternative `pandoc $FILE --to=pdf -o $NOTEVI/$1.pdf` can
# be used to convert current markdown file into pdf with LaTeX.


# $FILE   -> current file path
# $PARENT -> current directory path
# $PREFIX -> prefix name (titlepage)
# $NOTES  -> notes directory path

[[ -x "$(command -v pandoc)" ]] || exit 1
# ---
for NOTE in *; do
    [[ "${NOTE##*.}" == "md" ]] || continue
    NAME="${NOTE%.*}"
    pandoc "${NOTE}" -s --to=html5 -o "${NOTES}"/"${NAME}".html \
                --mathjax \
                --lua-filter="${NOTES}"/assets/link2html.lua \
                -H "${NOTES}"/assets/header.html \
                -B "${NOTES}"/assets/before.html \
                -A "${NOTES}"/assets/footer.html \
                -T "${PREFIX}" \
                &>/dev/null
done
